#!/usr/bin/env bash

options=(
  style=round
  width=6
  inactive_color=0xff494d64   # Catppuccin Mocha surface2
  active_color="glow(0xFFcba6f7)"  # Catppuccin Mocha mauve
  hidpi=on
)

borders "${options[@]}"
